---
  .travis.yml:
    hc_secure: "PTLMgcN2s0N1A4B5vpL5QyHI0YiJJBYHOFCc2DCTlGy+X27I4PhM5aCG7OOJ\nYefb63FmtQA+N3i6R/7G0tqJx3RemS4H5g9yauPsc6iI7zzxZa0azAtQecH+\n5nPTAKECRvof0dxltbde7AAAIlVdL3S/uXdAiItmPGaWGqxXrxk="

