name 'evenup-redis'
version '1.3.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Manages redis.'
description 'Installs, configures, and runs the redis service.'
project_page 'https://github.com/evenup/evenup-redis'
